version: "3.9"
services:
  # image micro-payment
  micro_payment:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    environment: 
      TZ: "${TZ:-America/Sao_Paulo}"
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis_micro_payment
    networks:
      - micropayment
  
  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl:/etc/nginx/ssl/
    networks:
      - micropayment

  # mysql micro_payment
  db_micro_payment:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - 3368:3306
    networks:
      - micropayment

  # redis
  redis_micro_payment:
    image: redis:latest
    networks:
      - micropayment

networks:
  micropayment:
    driver: bridge
